### ISSUE TITLE
Add animation for 'copy' in address dropdown

### ISSUE THREAD

**Issue by nathanjessen** [octofi/octofi-app-aquafarm#10]
In the dropdown on the top right, the user is able to 'copy' the currently connected ethereum address. But no indication is given that the copy was successful.

Add an animation of some sort to make it clear that the address was copied. Given that we copy ethereum addresses and contract addresses often when dealing with crypto, there needs to be a clear indicator when something has been copied successfully. If we don't do this, then we may be opening the user up to more user errors such as pasting the wrong address in a Swap or Send transaction which would cause loss of funds.

**Comment by octofi** [comment]
Thanks for your feedback, will be added in V2.0

**Comment by octofi** [comment]
Will be released in our update today
