### ISSUE TITLE
Prices shown aren't the best

### ISSUE THREAD

**Issue by ghost** [OctoFi/octofi-app-aquafarm#190]
[ ] This bug is for the dApp at app.octo.fi, not the website at octo.fi

**Please provide the following information for your Bug.**

Link to the page it occurred:

https://app.octo.fi/#/exchange

Description:

I was trying to swap some CEL for some NEXO and it seemed to work, it gave me two options 1inch and Bancor and after verifying on these sites themselves the prices it showed were good.. However I checked on uniswap and the price was about 3% better and that wasn't even shown as an option.

There was also Multipath given as an option but the price was NaN so seems broken

What did you expect to happen?

I expected so be shown the best price across all popular Dexes, uniswap missing is a biggie especially with a price difference that large.

I always check OCTO first as got high hopes for the project but I rarely end up using it as this happens with a lot of pairs.

Steps to reproduce the issue:
1. Go to Exchange page
2. Swap CEL for NEXO
3. Verify prices on suggested and other DEX's

Screenshots:

![octo](https://user-images.githubusercontent.com/7912050/127638155-0fdeba6a-2680-4d32-afe9-501d4b775811.png)

**Comment by nathanjessen** [comment]
Closed due to inactivity
