### ISSUE TITLE
The number NaN cannot be converted to BigInt because it is not an integer - first deployment 

### ISSUE THREAD

**Issue by BLT7** [OctoFi/octofi-app-aquafarm#195]
[ ] This bug is for the dApp at app.octo.fi, not the website at octo.fi

**Please provide the following information for your Bug.**

Link to the page it occurred:

Description:
Hi,

I followed the differents step to create template but i face an issue at the first deployment. RangeError: The number NaN cannot be converted to BigInt because it is not an integer

![image](https://user-images.githubusercontent.com/97528744/149040156-701b5c00-ea3b-4f95-a22e-bfbdfa6e1d98.png)

What did you expect to happen?
See the website homepage

Steps to reproduce the issue:
1. fork code
2. follow steps of deployment
3. yarn start
4. Error message on localhost:3000

Screenshots:
![image](https://user-images.githubusercontent.com/97528744/149040156-701b5c00-ea3b-4f95-a22e-bfbdfa6e1d98.png)

**Comment by cryptobsc** [comment]
Did you manage to fix it?!

**Comment by nathanjessen** [comment]
Closed due to inactivity
