### ISSUE TITLE
Breadcrumbs not working as intended

### ISSUE THREAD

**Issue by nathanjessen** [octofi/octofi-app-aquafarm#3]
**Problem**
All breadcrumbs link back to the homepage instead of the intended page.

**Desired behavior**
Each breadcrumb should link to the page that matches the name.

**Cause**
Issue stems from pulling pathname from the active nav link.

**Possible Solutions**
Use link hash to generate breadcrumb link.
Switch app to not use the hash router

**Comment by octofi** [comment]
Thanks for the feedback, will take a look into it. ^OG

**Comment by octofi** [comment]
Will be fixed with v2.0 and new frontend update
