### ISSUE TITLE
Ramp Instant defaults to GBP

### ISSUE THREAD

**Issue by nathanjessen** [octofi/octofi-app-aquafarm#6]
**Steps to Reproduce**

- Go to Buy Crypto
- Choose EUR as input currency, and any output asset
- Click 'Buy Crypto Asset' button

Notice that GBP is chosen as the input currency by Ramp Instant although EUR was chosen for input currency.

**Comment by octofi** [comment]
You're right, but I noticed it's automatically choosing the currency that is default in your browser settings / location. (or your VPN location)
