### ISSUE TITLE
Add external link for history transactions

### ISSUE THREAD

**Issue by nathanjessen** [octofi/octofi-app-aquafarm#7]
**Improvement Proposal**

In the History route, add an external link for each transaction when the user expands the line item. The transaction hash could be made to be a link to etherscan or a link icon could be placed next to it. I like that the transaction hash is just text because it makes it easier to select and copy. But I also would like the ability to click to open the transaction in etherscan.

**Comment by nathanjessen** [comment]
Addressed in today's update

**Comment by octofi** [comment]
Thanks for your feedback
